Update packages
cyclejs-community/cyclejs-modal pull request #25
Opened 2018-11-30 04:32 UTC by FeliciousX

2018-11-30 07:35 UTC, FeliciousX commented
updating cycle/dom breaks the example for rxjs :(

2018-12-04 02:45 UTC, kiyui requested changes
Minor changes required.

2018-12-04 02:45 UTC, TimurKiyivinski commented on examples/rxjs/src/index.ts
> +import { Observable, of as observableOf, pipe } from 'rxjs';
The `pipe` is not used here.
```suggestion
import { Observable, of as observableOf } from 'rxjs';
```

2018-12-04 02:45 UTC, TimurKiyivinski commented on examples/rxjs/src/index.ts
>  import { Stream } from 'xstream';
This can be removed.

2018-12-04 06:40 UTC, kiyui approved these changes
:slightly_smiling_face:

2018-12-04 06:43 UTC, jvanbruegge commented
Hi @FeliciousX, does this change still break the build? Or did I understand you wrong?

2018-12-04 06:59 UTC, FeliciousX commented
everything works fine :D @jvanbruegge just had to update the example

2018-12-04 07:01 UTC, FeliciousX commented
btw `browserify` is weird, the order of import matters

```typescript
import { run } from '@cycle/rxjs-run'
import { mapTo } from 'rxjs/operators'
```

must come first before importing rxjs operators.. otherwise it will cause a runtime error when we run the examples.

2018-12-04 07:02 UTC, FeliciousX commented
i skipped updating `cyclejs-utils` but i updated rxjs to the latest version

2018-12-04 07:03 UTC, jvanbruegge commented
Ok, i will merge an publish later this day, thank you

2018-12-04 07:05 UTC, FeliciousX commented
thank you @jvanbruegge  :grinning:

2018-12-04 13:28 UTC, merged

2018-12-04 14:02 UTC, jvanbruegge commented
Published as `v7.0.0`